UNSEEN_CLASSES = {
    "sketchy_1": [
        "cup",
        "swan",
        "harp",
        "squirrel",
        "snail",
        "ray",
        "pineapple",
        "volcano",
        "rifle",
        "scissors",
        "parrot",
        "windmill",
        "teddy_bear",
        "tree",
        "wine_bottle",
        "deer",
        "chicken",
        "hotdog",
        "wheelchair",
        "tank",
        "umbrella",
        "butterfly",
        "camel",
        "horse",
        "bell"
    ],

    "sketchy_2": [
        "bat",
        "cabin",
        "cow",
        "dolphin",
        "door",
        "giraffe",
        "helicopter",
        "mouse",
        "pear",
        "raccoon",
        "rhinoceros",
        "saw",
        "scissors",
        "seagull",
        "skyscraper",
        "songbird",
        "sword",
        "tree",
        "wheelchair",
        "windmill",
        "window",
    ],

    "quickdraw": [
        "airplane",
        "alarm_clock",
        "ant",
        "apple",
        "axe",
        "banana",
        "bat",
        "bear",
        "bee",
        "bench",
        "bicycle",
        "bread",
        "bus",
        "butterfly",
        "cactus",
        "cake",
        "camel",
        "candle",
        "car",
        "castle",
        "cat",
        "chair",
        "church",
        "couch",
        "cow",
        "crab",
        "crocodilian",
        "dolphin",
        "eyeglasses",
        "guitar",
    ],

    # "quickdraw": [
    #     "helicopter",
    #     "moon",
    #     "spider",
    #     "pineapple",
    #     "hammer",
    #     "banana",
    #     "owl",
    #     "teddy_bear",
    #     "scorpion",
    #     "chair",
    #     "motorcycle",
    #     "bread",
    #     "train",
    #     "butterfly",
    #     "palm tree",
    #     "cake",
    #     "zebra",
    #     "lighthouse",
    #     "pickup_truck",
    #     "church",
    #     "dog",
    #     "couch",
    #     "skyscraper",
    #     "sheep",
    #     "fan"
    #     "bee",
    #     "snake",
    #     "shark",
    #     "eyeglasses",
    #     "violin",
    # ],

    # "tuberlin": [
    #     "airplane",
    #     "alarm clock",
    #     "angel",
    #     "ant",
    #     "apple",
    #     "armchair",
    #     "axe",
    #     "backpack",
    #     "barn",
    #     "baseball bat",
    #     "bathtub",
    #     "bear (animal)",
    #     "bee",
    #     "beer-mug",
    #     "bell",
    #     "bicycle",
    #     "binoculars",
    #     "blimp",
    #     "bottle opener",
    #     "brain",
    #     "bus",
    #     "cactus",
    #     "calculator",
    #     "camel",
    #     "canoe",
    #     "car (sedan)",
    #     "castle",
    #     "chandelier",
    #     "cigarette",
    #     "computer monitor",
    # ]
    "tuberlin": [
        "helicopter",
        "wrist-watch",
        "mermaid",
        "mosquito",
        "pear",
        "couch",
        "hammer",
        "purse",
        "house",
        "tennis-racket",
        "toilet",
        "panda",
        "butterfly",
        "mug",
        "wineglass",
        "motorbike",
        "eyeglasses",
        "hot air balloon",
        "screwdriver",
        "skull",
        "truck",
        "palm tree",
        "cell phone",
        "horse",
        "sailboat",
        "suv",
        "church",
        "floor lamp",
        "pipe (for smoking)",
        "tv",
    ]

}
